### PR TITLE
Documentation updated to support capability "CreatePDFFromHTMLTemplate"

### PR DESCRIPTION
**Pull request by DivyaWal7**
## Description

 Updated documentation of creatpdf to support additional capability of  creating PDF files from HTML using a template engine. It utilizes a template engine to process HTML templates and generate the corresponding PDF output.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by cfjedimaster — COMMENTED** [review]
The approach documented here does not make sense for many reasons. Here are some issues:

* json is typically capitalized
* HTML doesn't have JSON fields. I believe you were trying to suggest dynamic fields that are replaced with data, but "json fields" is not correct terminology.
* The source HTML should *not* include a library. We discussed this in Slack, but the processing is done outside of HTML.
* Also, it implies Mustache is the only way to do it.
* The code samples are all basic "html to pdf with sdk/api", this is no different (if I'm reading right) from earlier code samples.

As we talked about, I do think the core docs should mention the new sample, when it's available, but it should be *very* short, just a paragraph linking to the new sample. 

Can we talk about this via Slack?

**Comment by DivyaWal7** [comment]
Sure @cfjedimaster, we can discuss this.

**Comment by DivyaWal7** [comment]
@cfjedimaster  Please find the corrections as made inline

> * json is typically capitalized
     _**Updated this**_
> * HTML doesn't have JSON fields. I believe you were trying to suggest dynamic fields that are replaced with data, but "json fields" is not correct terminology.
 _**Updated the terminology**_
> * The source HTML should _not_ include a library. We discussed this in Slack, but the processing is done outside of HTML.
_**As discussed, we cannot expose the functionality /conversion logic as part of the samples code. It has to be handled as part of the api /engine code only.Therefore we need to include the library in the HTML file to support conversion before processing of the HTML at engine side**._
> * Also, it implies Mustache is the only way to do it.
_**Mustache is one of the template engines that we are suggesting, definitely we can include 1-2 additional samples depicting different template engines that the client can  make use of.**_
> * The code samples are all basic "html to pdf with sdk/api", this is no different (if I'm reading right) from earlier code samples.
_**Yes i have used the exisiting samples used in html to pdf only with minor modifications of using the tags instead of the actual values**_

> As we talked about, I do think the core docs should mention the new sample, when it's available, but it should be _very_ short, just a paragraph linking to the new sample.
_**Yes, can definitely do that , let me know if i should create new samples for both the template engines (FYI, currently only 1 template engine is included) or use the existing sample with minor modifications.**_

**Comment by cfjedimaster** [comment]
I still strongly disagree with this approach. Can we setup a meeting with all interested parties?

**Comment by DivyaWal7** [comment]
Closing this PR

**Pull request closed without merging**
